# Generated by Django 2.2.6 on 2019-12-26 02:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flower',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='Name')),
                ('group', models.CharField(max_length=32, verbose_name='Name')),
            ],
        ),
        migrations.CreateModel(
            name='Market',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt', models.DateField(verbose_name='Date')),
                ('p1', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Low Price')),
                ('p2', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='High Price')),
                ('flower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kifa.Flower')),
            ],
            options={
                'unique_together': {('dt', 'flower')},
            },
        ),
    ]
