# Generated by Django 2.2.6 on 2019-12-26 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kifa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flower',
            name='group',
            field=models.CharField(max_length=32, verbose_name='Group'),
        ),
    ]
