# Generated by Django 2.2.6 on 2019-10-05 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0002_note_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='seq',
            field=models.IntegerField(default=0),
        ),
    ]
