# Generated by Django 2.2.6 on 2019-10-10 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0003_note_seq'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note002',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail002', models.TextField(max_length=200)),
                ('note', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='note.Note')),
            ],
        ),
    ]
