# Generated by Django 2.2.6 on 2019-10-10 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0004_note002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note002',
            name='detail002',
        ),
        migrations.AddField(
            model_name='note002',
            name='whatever',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='note002',
            name='note',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='note.Note'),
        ),
    ]
