# Generated by Django 2.2.6 on 2019-11-01 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date1', models.DateField()),
                ('place', models.CharField(max_length=100)),
                ('worker', models.CharField(max_length=100)),
                ('thing', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Data2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('member', models.CharField(max_length=6)),
                ('date1', models.DateField()),
                ('role', models.CharField(max_length=32)),
                ('points', models.IntegerField(default=0)),
            ],
            options={
                'unique_together': {('name', 'date1', 'member')},
            },
        ),
        migrations.CreateModel(
            name='Best',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date1', models.DateField()),
                ('title', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=32)),
            ],
            options={
                'unique_together': {('date1', 'title')},
            },
        ),
    ]
