# Generated by Django 2.2.6 on 2019-11-01 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('case005', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Data1',
        ),
        migrations.AlterModelOptions(
            name='best',
            options={'verbose_name': 'Meeting Best', 'verbose_name_plural': 'Meeting Best'},
        ),
        migrations.AlterModelOptions(
            name='data2',
            options={'verbose_name': 'Meeting', 'verbose_name_plural': 'Meeting'},
        ),
    ]
