# Generated by Django 2.2.6 on 2019-11-04 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case005', '0003_auto_20191101_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='best',
            name='title',
            field=models.CharField(choices=[('tt', 'tt')], default='tt', max_length=32),
        ),
        migrations.AlterField(
            model_name='data2',
            name='member',
            field=models.CharField(choices=[('Member', 'Member'), ('Guest', 'Guest')], max_length=6),
        ),
        migrations.AlterField(
            model_name='data2',
            name='role',
            field=models.CharField(choices=[('---', '---'), ('Ah-counter', 'Ah-counter'), ('GE', 'GE'), ('Grammarian', 'Grammarian'), ('IE', 'IE'), ('Speaker', 'Speaker'), ('TME', 'TME'), ('TT Speaker', 'TT Speaker'), ('TT Evaluator', 'TT Evaluator'), ('TT-master', 'TT-master'), ('Timer', 'Timer')], max_length=32),
        ),
    ]
