# Generated by Django 2.2.6 on 2019-11-01 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case005', '0003_auto_20191101_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='best',
            name='title',
            field=models.CharField(choices=[('tt', 'tt')], default='tt', max_length=32),
        ),
    ]
