# Generated by Django 2.2.6 on 2019-11-01 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case005', '0004_auto_20191101_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data2',
            name='member',
            field=models.CharField(choices=[('Member', 'Member'), ('Guest', 'Guest')], max_length=6),
        ),
    ]
