# Generated by Django 2.2.6 on 2019-11-07 06:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case005', '0004_auto_20191104_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data2',
            name='date1',
            field=models.DateField(default=datetime.date.today, verbose_name='Meeting Date'),
        ),
        migrations.AlterField(
            model_name='data2',
            name='member',
            field=models.CharField(choices=[('Member', 'Member'), ('Guest', 'Guest')], max_length=6, verbose_name='Member or Guess'),
        ),
        migrations.AlterField(
            model_name='data2',
            name='role',
            field=models.CharField(choices=[('---', '---'), ('Ah-counter', 'Ah-counter'), ('GE', 'GE'), ('Grammarian', 'Grammarian'), ('IE', 'IE'), ('Speaker', 'Speaker'), ('TME', 'TME'), ('TT Speaker', 'TT Speaker'), ('TT Evaluator', 'TT Evaluator'), ('TT-master', 'TT-master'), ('Timer', 'Timer')], max_length=32, verbose_name='Meeting Role'),
        ),
    ]
