# Generated by Django 2.2.6 on 2019-11-07 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case005', '0005_auto_20191107_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data2',
            name='role',
            field=models.CharField(choices=[('Attendance', 'Attendance'), ('Ah-counter', 'Ah-counter'), ('GE', 'GE'), ('Grammarian', 'Grammarian'), ('IE', 'IE'), ('Speaker', 'Speaker'), ('TME', 'TME'), ('TT Speaker', 'TT Speaker'), ('TT Evaluator', 'TT Evaluator'), ('TT-master', 'TT-master'), ('Timer', 'Timer')], max_length=32, verbose_name='Meeting Role'),
        ),
    ]
