# Generated by Django 2.2.6 on 2019-11-07 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('case005', '0006_auto_20191101_1655'),
        ('case005', '0006_auto_20191107_1508'),
    ]

    operations = [
    ]
