# Generated by Django 2.2.6 on 2019-11-07 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('case005', '0008_auto_20191107_1518'),
        ('case005', '0007_auto_20191107_2206'),
    ]

    operations = [
    ]
