# Generated by Django 2.2.6 on 2019-11-18 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case005', '0011_club'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='fullname',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='club',
            name='name',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
