# Generated by Django 2.2.6 on 2019-11-18 01:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('case005', '0012_auto_20191118_0932'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='club',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='case005.Club'),
        ),
    ]
