# Generated by Django 2.2.6 on 2019-11-18 01:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('case005', '0013_meeting_club'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('fullname', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PersonClub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='case005.Club')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='case005.Person')),
            ],
        ),
    ]
