# Generated by Django 2.2.6 on 2019-11-18 02:41

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('case005', '0015_meeting_person'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClubDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date1', models.DateField(default=datetime.date.today, verbose_name='Meeting Date')),
                ('note', models.CharField(default='---', max_length=32)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='case005.Club')),
            ],
            options={
                'unique_together': {('date1', 'club')},
            },
        ),
    ]
