# Generated by Django 2.2.6 on 2019-11-18 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case005', '0016_clubdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
                ('fullname', models.CharField(max_length=100, unique=True)),
            ],
        ),
    ]
