# Generated by Django 2.2.6 on 2019-11-18 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case005', '0020_person_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='fullname',
            field=models.CharField(max_length=100),
        ),
    ]
