# Generated by Django 2.2.6 on 2019-11-18 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case005', '0023_auto_20191118_1204'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ['-is_member', 'name']},
        ),
        migrations.AddField(
            model_name='person',
            name='is_member',
            field=models.BooleanField(default=False, verbose_name='Is Member '),
        ),
    ]
