# Generated by Django 2.2.6 on 2019-11-18 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('case005', '0024_auto_20191118_1544'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meeting',
            options={},
        ),
    ]
