# Generated by Django 2.2.6 on 2019-11-23 03:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('case005', '0025_auto_20191118_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='club',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='case005.Club'),
        ),
    ]
