# Generated by Django 2.2.6 on 2019-11-23 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('case005', '0026_person_club'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PersonClub',
        ),
    ]
