# Generated by Django 2.2.6 on 2019-11-29 03:03

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('case005', '0027_delete_personclub'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='date1',
            field=models.DateField(default=datetime.date.today, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='role2',
            field=models.ForeignKey(default=12, on_delete=django.db.models.deletion.CASCADE, to='case005.Role', verbose_name='Role'),
        ),
    ]
