# Generated by Django 2.2.6 on 2019-12-26 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flower',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='Name')),
                ('group', models.CharField(max_length=32, verbose_name='Group')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.IntegerField(unique=True)),
                ('event_id', models.IntegerField()),
                ('department', models.CharField(default='---', max_length=32)),
                ('work_no', models.IntegerField()),
                ('work_name', models.CharField(default='---', max_length=32)),
                ('status', models.CharField(default='---', max_length=32)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('reason', models.CharField(blank=True, max_length=100, null=True)),
                ('improvement', models.CharField(blank=True, max_length=100, null=True)),
                ('deal_type', models.CharField(blank=True, max_length=32, null=True)),
            ],
        ),
    ]
