# Generated by Django 2.2.6 on 2019-12-20 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=32)),
                ('phone', models.CharField(max_length=11)),
                ('clubtxt', models.CharField(max_length=100)),
                ('note', models.CharField(max_length=100)),
                ('feetxt', models.CharField(max_length=100)),
                ('stattxt', models.CharField(max_length=100)),
                ('dt', models.DateTimeField()),
            ],
        ),
    ]
