# Generated by Django 2.2.6 on 2019-12-20 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taicang', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='club',
            field=models.CharField(default='---', max_length=100),
        ),
    ]
