# Generated by Django 2.2.6 on 2019-12-14 01:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('persontxt', models.CharField(max_length=32, verbose_name='Name')),
                ('date1', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('note', models.CharField(blank=True, max_length=32, null=True, verbose_name='Note')),
            ],
            options={
                'unique_together': {('persontxt', 'date1')},
            },
        ),
    ]
