# Generated by Django 2.2.6 on 2019-12-14 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reading', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meeting',
            old_name='persontxt',
            new_name='name',
        ),
        migrations.AlterUniqueTogether(
            name='meeting',
            unique_together={('name', 'date1')},
        ),
    ]
