# Generated by Django 2.2.6 on 2019-11-29 05:07

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
                ('fullname', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
                ('fullname', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('fullname', models.CharField(max_length=100)),
                ('is_member', models.BooleanField(default=False, verbose_name='Is Member ')),
                ('member_since', models.DateField(blank=True, null=True, verbose_name='Member Since')),
                ('note', models.CharField(blank=True, max_length=100, null=True)),
                ('club', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='clubs.Club')),
            ],
            options={
                'ordering': ['-is_member', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Data2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('member', models.CharField(choices=[('Member', 'Member'), ('Guest', 'Guest')], max_length=6, verbose_name='Member or Guest')),
                ('date1', models.DateField(default=datetime.date.today, verbose_name='Meeting Date')),
                ('role', models.CharField(choices=[('Attendance', 'Attendance'), ('Ah-counter', 'Ah-counter'), ('GE', 'GE'), ('Grammarian', 'Grammarian'), ('IE', 'IE'), ('Speaker', 'Speaker'), ('TME', 'TME'), ('TT Speaker', 'TT Speaker'), ('TT Evaluator', 'TT Evaluator'), ('TT-master', 'TT-master'), ('Timer', 'Timer')], max_length=32, verbose_name='Meeting Role')),
                ('points', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Meeting',
                'verbose_name_plural': 'Meeting',
                'unique_together': {('name', 'date1', 'member', 'role')},
            },
        ),
        migrations.CreateModel(
            name='Best',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date1', models.DateField()),
                ('title', models.CharField(choices=[('tt', 'tt')], default='tt', max_length=32)),
                ('name', models.CharField(max_length=32)),
            ],
            options={
                'verbose_name': 'Meeting Best',
                'verbose_name_plural': 'Meeting Best',
                'unique_together': {('date1', 'title')},
            },
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date1', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('club', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='clubs.Club')),
                ('person', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='clubs.Person')),
                ('role2', models.ForeignKey(default=12, on_delete=django.db.models.deletion.CASCADE, to='clubs.Role', verbose_name='Role')),
            ],
            options={
                'unique_together': {('person', 'date1', 'role2')},
            },
        ),
        migrations.CreateModel(
            name='ClubDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date1', models.DateField(default=datetime.date.today, verbose_name='Meeting Date')),
                ('note', models.CharField(default='---', max_length=32)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubs.Club')),
            ],
            options={
                'unique_together': {('date1', 'club')},
            },
        ),
    ]
