# Generated by Django 2.2.6 on 2019-11-29 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Data2',
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ['club', 'name']},
        ),
    ]
