# Generated by Django 2.2.6 on 2019-11-29 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0002_auto_20191129_1414'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='person',
            unique_together={('club', 'name')},
        ),
    ]
