# Generated by Django 2.2.6 on 2019-11-30 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0003_auto_20191129_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='persontxt',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubs.Club'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubs.Person'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='role2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubs.Role', verbose_name='Role'),
        ),
    ]
