# Generated by Django 2.2.6 on 2019-12-01 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0004_auto_20191130_1752'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='firstname',
            field=models.CharField(default='---', max_length=32),
        ),
        migrations.AddField(
            model_name='person',
            name='lastname',
            field=models.CharField(default='---', max_length=32),
        ),
        migrations.AddField(
            model_name='person',
            name='member_type',
            field=models.CharField(default='---', max_length=32),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='persontxt',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Name'),
        ),
    ]
