# Generated by Django 2.2.6 on 2019-12-01 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0006_person_member_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='email',
            field=models.EmailField(blank=True, max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='phone',
            field=models.CharField(default='---', max_length=11),
        ),
    ]
