# Generated by Django 2.2.6 on 2019-12-01 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0008_person_sponsor_mentor'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='officer',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
