# Generated by Django 2.2.6 on 2019-12-02 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0009_person_officer'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='teamleader',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
