# Generated by Django 2.2.6 on 2019-12-02 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0010_person_teamleader'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='teamnote',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
